# Generated by Django 4.2.6 on 2023-12-28 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='address',
            field=models.CharField(default='abcd', max_length=800),
        ),
        migrations.AddField(
            model_name='newuser',
            name='city',
            field=models.CharField(default='hubli', max_length=500),
        ),
        migrations.AddField(
            model_name='newuser',
            name='contact_number',
            field=models.CharField(default='9876543210', max_length=100),
        ),
        migrations.AddField(
            model_name='newuser',
            name='country',
            field=models.CharField(default='India', max_length=400),
        ),
        migrations.AddField(
            model_name='newuser',
            name='landmark',
            field=models.CharField(default='xyz', max_length=600),
        ),
        migrations.AddField(
            model_name='newuser',
            name='state',
            field=models.CharField(default='Karnakata', max_length=300),
        ),
        migrations.AddField(
            model_name='newuser',
            name='status',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='user_type',
            field=models.CharField(default='Tenant', max_length=100),
        ),
    ]
