# Generated by Django 4.2.6 on 2023-12-28 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_newuser_address_newuser_city_newuser_contact_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='area',
            field=models.CharField(default='xyz', max_length=600),
        ),
    ]
